app/config/urls.py
from django.contrib import admin
from django.urls import path, include
from core.homepage.views import IndexView
from core.login.views import *

from django.conf import settings
from django.conf.urls.static import static
#urls principales del proyecto APPS
urlpatterns = [
    path('', IndexView.as_view(), name='index'), #url de pagina principal
    path('login/', include('core.login.urls')), #url de inision de sesion
    path('admin/', admin.site.urls), #url de usuarios
    path('erp/', include('core.erp.urls')),
    path('reports/', include('core.reports.urls')), #url de reportes
    path('user/', include('core.user.urls')), #url general para ir a listado de usuarios
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/core/erp/urls.py
from django.urls import path
from core.erp.views.category.views import *
from core.erp.views.client.views import *
from core.erp.views.dashboard.views import *
from core.erp.views.product.views import *
from core.erp.views.tests.views import TestView
from core.erp.views.sale.views import SaleCreateView,SaleListView,SaleDeleteView,SaleUpdateView,SaleInvoicePdfView #importando las vistas de las ventas



app_name = 'erp'

urlpatterns = [
    # category
    path('category/list/', CategoryListView.as_view(), name='category_list'),
    path('category/add/', CategoryCreateView.as_view(), name='category_create'),
    path('category/update/<int:pk>/', CategoryUpdateView.as_view(), name='category_update'),
    path('category/delete/<int:pk>/', CategoryDeleteView.as_view(), name='category_delete'),
    # client
    path('client/list/', ClientListView.as_view(), name='client_list'),
    path('client/add/', ClientCreateView.as_view(), name='client_create'),
    path('client/update/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    path('client/delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),
    # product
    path('product/list/', ProductListView.as_view(), name='product_list'),
    path('product/add/', ProductCreateView.as_view(), name='product_create'),
    path('product/update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('product/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
    # home
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    # test
    path('test/', TestView.as_view(), name='test'),
    # sale o ventas
    path('sale/list/', SaleListView.as_view(), name='sale_list'),
    path('sale/add/', SaleCreateView.as_view(), name='sale_create'),
    path('sale/delete/<int:pk>/', SaleDeleteView.as_view(), name='sale_delete'),
    path('sale/update/<int:pk>/', SaleUpdateView.as_view(), name='sale_update'),
    #url para visualizar la factura en pdf
    path('sale/invoice/pdf/<int:pk>/', SaleInvoicePdfView.as_view(), name='sale_invoice_pdf'),

]

app/core/user/urls.py
from django.urls import path
from core.user.views import *
# importando la vista de listado de usuarios
from core.user.views import UserListView
# importando la vista del formulario para crear usuario y editar 
from core.user.views import UserCreateView, UserUpdateView, UserDeleteView,UserChangeGroup
# importando la vista del formulario de editar el usuario actual logueado
from core.user.views import UserProfileView
# importando la vista para editar conseña en sesion actual
from core.user.views import UserChangePasswordView

app_name = 'user'

urlpatterns = [
    # ver listados de usuario
    path('list/', UserListView.as_view(), name='user_list'),
    # crear usuarios nuevos
    path('add/', UserCreateView.as_view(), name='user_create'),
    # editar usuario
    path('update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    # eliminar usuarios
    path('delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),
    # visualizar rol seleccionado o grupo durante la secion
    path('change/group/<int:pk>/', UserChangeGroup.as_view(), name='user_change_group'),
    # Ver el formulario para editar datos del usuario logueado
    path('profile/', UserProfileView.as_view(), name='user_profile'),
    #url para editar la contraseña del logueado actual con el formulario de django por default
    path('change/password/', UserChangePasswordView.as_view(), name='user_change_password'),
]

app/templates/vtc/body.html
{% extends 'home.html' %}
{% block body %}
    <body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        <!-- Header -->
        {% include 'vtc/header.html' %}
        <!-- Sidebar -->
        {% include 'vtc/sidebar.html' %}
        <!-- Content -->
        <div class="content-wrapper">
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark"> Bienvenido <small>{{ request.user.get_full_name }}</small></h1>
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="{% url 'erp:dashboard' %}">Home</a></li>
                                <li class="breadcrumb-item"><a href="{{ list_url }}">{{ entity }}</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="container-fluid">
                    {% block content %}

                    {% endblock %}
                </div>
            </div>
        </div>
        <!-- Footer -->
        {% include 'footer.html' %}
    </div>
    <!-- Block javascript -->
    {% block javascript %}

    {% endblock %}
    <script>
        {% if messages %}
            var html = '<p>';
            {% for message in messages %}
                html += '{{ message }}<br>';
            {% endfor %}
            html += '</p>';
            Swal.fire({
                title: 'Error!',
                html: html,
                icon: 'error'
            });
        {% endif %}
    </script>
    </body>
{% endblock %}

app/templates/vtc/header.html
<nav class="main-header navbar navbar-expand navbar-dark navbar-primary">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="{% url 'erp:dashboard' %}" class="nav-link">Home</a>
        </li>
    </ul>
    <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">
        <!-- vlidando si tiene rol o no el usuario-->
        {% if request.user.groups.all %}
            <li class="nav-item dropdown">
                <!--  if request.user.groups.all.count > 1 %} dropdown-toggle Validacion para quitar la flechita de la lista cuando el usuario solo tiene 1 grupo o rol-->
                <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                   class="nav-link{% if request.user.groups.all.count > 1 %} dropdown-toggle{% endif %}">{{ request.session.group }}</a>
                <!-- Validacion de cantidad de roles que tiene un usuario -->
                {% if request.user.groups.all.count > 1 %}
                    <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow"
                        style="left: 0px; right: inherit;">
                        {% for g in request.user.groups.all %}
                            <!-- colocando el nombre del grupo o rol -->
                            <!-- Validacion para mostrar el nombre del rol en el header sin repetir el ombre en lista y header-->
                            {% if g.id != request.session.group.id %}
                                <!--g.id es el parametro o clave que el urls.py solicita el direccionamiento -->
                                <li><a href="{% url 'user:user_change_group' g.id %}"
                                       class="dropdown-item">{{ g.name }} </a></li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                {% endif %}
            </li>
        {% endif %}

        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="fas fa-users-cog"></i> {{ request.user.username }}
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <span class="dropdown-header" style="font-size: 12px;">
                    {#                      la clase   request muestra al suario logueado#}
                        Sú último acceso fue {{ request.user.last_login }}
                    </span>
                <div class="dropdown-divider"></div>
                <!-- Nombre de url para editar los datos  de usuario actual sin afectar el logueo-->
                <a href="{% url 'user:user_profile' %}" class="dropdown-item">
                    <i class="fas fa-edit mr-2"></i> Editar perfil
                    <span class="float-right text-muted text-sm">3 mins</span>
                </a>
                <div class="dropdown-divider"></div>
                <!-- Nombre de url para editar password de usuario actual sin afectar el logueo-->
                <a href="{% url 'user:user_change_password' %}" class="dropdown-item">
                    <i class="fas fa-lock mr-2"></i> Editar password
                    <span class="float-right text-muted text-sm">12 hours</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">
                    <p>Este sistema te permitira realizar diferentes actividades</p>
                </a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">
                <i class="fas fa-power-off" aria-hidden="true"></i>
            </a>
        </li>
    </ul>
</nav>

app/templates/vtc/sidebar.html
{% load static %}
<aside class="main-sidebar sidebar-light-primary elevation-4">
    <a href="{% url 'erp:dashboard' %}" class="brand-link">
        <img src="{% static 'img/logo.png' %}"
             alt="AdminLTE Logo"
             class="brand-image img-circle elevation-3"
             style="opacity: .8">
        <span class="brand-text font-weight-light">Hades</span>
    </a>
    <div class="sidebar">
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{{ request.user.get_image }}" class="img-circle" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">{{ request.user.username }}</a>
            </div>
        </div>
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-header">Mantenimientos</li>
{#                agregando icono y enlace para ir a listado de usuarios#}
                <li class="nav-item">
                    <a href="{% url 'user:user_list' %}" class="nav-link">
                        <i class="nav-icon fas fa-user-friends"></i>
                        <p>
                            Usuarios
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'erp:category_list' %}" class="nav-link">
                        <i class="nav-icon fas fa-truck-loading"></i>
                        <p>
                            Categorías
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'erp:product_list' %}" class="nav-link">
                        <i class="nav-icon fas fa-boxes"></i>
                        <p>
                            Productos
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'erp:client_list' %}" class="nav-link">
                        <i class="nav-icon fas fa-users"></i>
                        <p>
                            Clientes
                        </p>
                    </a>
                </li>
                <li class="nav-item"> <!--Url de ventas-->
                    <a href="{% url 'erp:sale_list' %}" class="nav-link">
                        <i class="nav-icon fas fa-shopping-cart"></i>
                        <p>
                            Ventas
                        </p>
                    </a>
                </li>
                <!-- Reportes de ventas -->
                <li class="nav-item">
                    <a href="{% url 'sale_report' %}" class="nav-link">
                        <i class="nav-icon fas fa-chart-bar"></i>
                        <p>
                            Reporte de Ventas
                        </p>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</aside>